import type { SupportedTtsLocale } from "@/domain/card-audio"

export const TTS_LANGUAGE_NATIVE_LABELS = {
  "en-US": "English",
  "ja-JP": "日本語",
  "zh-CN": "中文",
  "de-DE": "Deutsch",
  "hi-IN": "हिन्दी",
  "fr-FR": "Français",
  "ko-KR": "한국어",
  "pt-BR": "Português",
  "it-IT": "Italiano",
  "es-ES": "Español",
  "id-ID": "Bahasa Indonesia",
  "nl-NL": "Nederlands",
  "tr-TR": "Türkçe",
  "fil-PH": "Filipino",
  "pl-PL": "Polski",
  "sv-SE": "Svenska",
  "bg-BG": "Български",
  "ro-RO": "Română",
  "ar-SA": "العربية",
  "cs-CZ": "Čeština",
  "el-GR": "Ελληνικά",
  "fi-FI": "Suomi",
  "hr-HR": "Hrvatski",
  "ms-MY": "Bahasa Melayu",
  "sk-SK": "Slovenčina",
  "da-DK": "Dansk",
  "ta-IN": "தமிழ்",
  "uk-UA": "Українська",
  "ru-RU": "Русский",
} satisfies Record<SupportedTtsLocale, string>
